### ISSUE TITLE
YUI compressor does not install

### ISSUE THREAD

**Issue by AnotherKamila** [cjohansen/juicer#36]
I am getting the following error when attempting to install yui_compressor:

```
/usr/lib/ruby/gems/1.9.1/gems/juicer-1.0.12/lib/juicer/install/yui_compressor_installer.rb:65:in `latest': undefined method `[]' for nil:NilClass (NoMethodError)
    from /usr/lib/ruby/gems/1.9.1/gems/juicer-1.0.12/lib/juicer/command/install.rb:57:in `version'
    from /usr/lib/ruby/gems/1.9.1/gems/juicer-1.0.12/lib/juicer/command/install.rb:42:in `block in execute'
    from /usr/lib/ruby/gems/1.9.1/gems/juicer-1.0.12/lib/juicer/command/install.rb:39:in `each'
    from /usr/lib/ruby/gems/1.9.1/gems/juicer-1.0.12/lib/juicer/command/install.rb:39:in `execute'
    from /usr/lib/ruby/gems/1.9.1/gems/cmdparse-2.0.3/lib/cmdparse.rb:436:in `parse'
    from /usr/lib/ruby/gems/1.9.1/gems/juicer-1.0.12/lib/juicer/cli.rb:27:in `parse'
    from /usr/lib/ruby/gems/1.9.1/gems/juicer-1.0.12/lib/juicer/cli.rb:37:in `run'
    from /usr/lib/ruby/gems/1.9.1/gems/juicer-1.0.12/bin/juicer:6:in `<top (required)>'
    from /usr/bin/juicer:19:in `load'
    from /usr/bin/juicer:19:in `<main>'
```

**Comment by sgtpep** [comment]
The same for me on Mac OS X / rvm / Ruby 1.9.2. Recent versions fails to install yui_compressor, too.

**Comment by cjohansen** [comment]
YUI changed the download website. I just pushed 1.0.13 to RubyGems. Install it and try again.

**Comment by gametbt** [comment]
I have the same issue with the latest install:

$ juicer install yui_compressor
/usr/local/ruby-1.9.3-rc1/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
/usr/local/ruby-1.9.3-rc1/lib/ruby/gems/1.9.1/gems/juicer-1.0.13/lib/juicer/install/yui_compressor_installer.rb:65:in`latest': undefined method `[]' for nil:NilClass (NoMethodError)
    from /usr/local/ruby-1.9.3-rc1/lib/ruby/gems/1.9.1/gems/juicer-1.0.13/lib/juicer/command/install.rb:57:in`version'
    from /usr/local/ruby-1.9.3-rc1/lib/ruby/gems/1.9.1/gems/juicer-1.0.13/lib/juicer/command/install.rb:42:in `block in execute'
    from /usr/local/ruby-1.9.3-rc1/lib/ruby/gems/1.9.1/gems/juicer-1.0.13/lib/juicer/command/install.rb:39:in`each'
    from /usr/local/ruby-1.9.3-rc1/lib/ruby/gems/1.9.1/gems/juicer-1.0.13/lib/juicer/command/install.rb:39:in `execute'
    from /usr/local/ruby-1.9.3-rc1/lib/ruby/gems/1.9.1/gems/cmdparse-2.0.3/lib/cmdparse.rb:436:in`parse'
    from /usr/local/ruby-1.9.3-rc1/lib/ruby/gems/1.9.1/gems/juicer-1.0.13/lib/juicer/cli.rb:27:in `parse'
    from /usr/local/ruby-1.9.3-rc1/lib/ruby/gems/1.9.1/gems/juicer-1.0.13/lib/juicer/cli.rb:37:in`run'
    from /usr/local/ruby-1.9.3-rc1/lib/ruby/gems/1.9.1/gems/juicer-1.0.13/bin/juicer:6:in `<top (required)>'
    from /usr/local/ruby/bin/juicer:19:in`load'
    from /usr/local/ruby/bin/juicer:19:in `<main>'

**Comment by cjohansen** [comment]
Maybe it's because of 1.9.3? Didn't try on that. Works with juicer 1.0.13 on my end.
